sudo: required

dist: trusty

language: cpp

env:
    - SOURCE_PATH=~/dependency_source
    - BUILD_PATH=~/dependency_build
    - GTEST=gtest
    - GBENCH=gbench

# Build the dependencies. 
install: ./install_script.sh $SOURCE_PATH $GTEST $GBENCH $BUILD_PATH $GTEST $GBENCH 

before_script:  
    - mkdir build
    - cd build
    - cmake -DGTEST_BUILD_DIR=$BUILD_PATH/$GTEST -DGBENCH_BUILD_DIR=$BUILD_PATH/$GBENCH -DGTEST_SOURCE_DIR=$SOURCE_PATH/$GTEST -DGBENCH_SOURCE_DIR=$SOURCE_PATH/$GBENCH -DCMAKE_BUILD_TYPE=Release ..

script: 
    - cmake --build
    - ctest -VV




