sudo: required

dist: trusty

language: cpp

install: ./install_script.sh ~/dependency_source gtest gbench ~/dependency_build gtest gbench

before_script:  
    - mkdir build
    - cd build
    - cmake -DGTEST_BUILD_DIR=~/dependency_build/gtest -DGBENCH_BUILD_DIR=~/dependency_build/gbench -DGTEST_SOURCE_DIR=~/dependency_source/gtest -DGBENCH_SOURCE_DIR=~/dependency_source/gbench -DCMAKE_BUILD_TYPE=Release ..

script: make 




