opsudo: required

dist: trusty

language: cpp

install: ./install_script.sh build รง googlebench_build

before_script:  
    - mkdir build
    - cd build
    - cmake -DGTEST_BUILD_DIR=googletest_build -DGBENCH_BUILD_DIR=googlebench_build -DCMAKE_BUILD_TYPE=Release ..

script: make 




