sudo: required

dist: trusty

language: cpp

install: ./install_script.sh dependency_build googletest_build googlebench_build

before_script:  
    - mkdir build
    - cd build
    - cmake -DGTEST_BUILD_DIR=dependency_build/googletest_build -DGBENCH_BUILD_DIR=dependency_build/googlebench_build -DCMAKE_BUILD_TYPE=Release ..

script: make 




