sudo: required

dist: trusty

language: cpp

compiler: gcc

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libboost-dev
    - sudo apt-get install -y mpi-default-dev
    - sudo apt-get install -y libboost-mpi-dev
    - sudo apt-get install -y openmpi-bin


install: ./install_script.sh ~/dependency_source gtest gbench eigen ~/dependency_build gtest gbench

before_script:  
    - mkdir build
    - cd build
    - cmake -DGTEST_BUILD_DIR=~/dependency_build/gtest -DGBENCH_BUILD_DIR=~/dependency_build/gbench -DGTEST_SOURCE_DIR=~/dependency_source/gtest -DGBENCH_SOURCE_DIR=~/dependency_source/gbench -DEIGEN_ADDITIONAL_SEARCH_PATHS=~/dependency_source/eigen -DCMAKE_BUILD_TYPE=Release ..

script: 
    - cmake --build .
    - ctest -VV

